Homework 2
kalimullina/RenataKalimullina pull request #3
Opened 2021-08-24 17:08 UTC by kalimullina

2021-08-26 14:59 UTC, ZeroShadows commented
general comment 
lets create abstract base test class and move test setup, test tear down and driver initialisation there

2021-08-26 15:38 UTC, ZeroShadows requested changes

2021-08-26 15:38 UTC, ZeroShadows commented on src/test/java/com/epam/tc/hw2/Ex1.java
> +public class Ex1 {
rename test class with specific name

2021-08-26 15:38 UTC, ZeroShadows commented on src/test/java/com/epam/tc/hw2/Ex1.java
> +        webDriver.manage().window().maximize();
move it to test setup

2021-08-26 15:38 UTC, ZeroShadows commented on src/test/java/com/epam/tc/hw2/Ex1.java
> +    private WebElement webElement;
why do you need it as class field?

2021-08-26 15:38 UTC, ZeroShadows commented on src/test/java/com/epam/tc/hw2/Ex1.java
> +        webElement = webDriver.findElement(By.xpath("/html/body/div/div[2]/main/div[2]/div[2]/div[1]/div/span"));
you could use var variableName for that.
From my point of view it's a bit strange to use one WebElement variable for the whole test

2021-08-26 15:38 UTC, ZeroShadows commented on src/test/java/com/epam/tc/hw2/Ex1.java
> +        webElement = webDriver.findElement(By.xpath("/html/body/div/div[2]/main/div[2]/div[2]/div[2]/div/span"));
same for variable here

2021-08-26 15:38 UTC, ZeroShadows commented on src/test/java/com/epam/tc/hw2/Ex1.java
> +        webElement = webDriver.findElement(By.xpath("/html/body/div/div[2]/main/div[2]/div[2]/div[3]/div/span"));
same for variable here

2021-08-26 15:38 UTC, ZeroShadows commented on src/test/java/com/epam/tc/hw2/Ex1.java
> +        webElement = webDriver.findElement(By.xpath("/html/body/div/div[2]/main/div[2]/div[2]/div[4]/div/span"));
same for variable here

2021-08-26 15:38 UTC, ZeroShadows commented on src/test/java/com/epam/tc/hw2/Ex2.java
> +public class Ex2 {
same comments as in Ex1

2021-08-26 15:38 UTC, ZeroShadows commented on src/test/resources/hw2/Ex1Suite.xml
> +      <class name="com.epam.tc.hw2.Ex1"/>
add second test class here and remove Ex2.xml

2021-08-26 23:48 UTC, kalimullina commented on src/test/java/com/epam/tc/hw2/Ex1.java
> +public class Ex1 {
fixed

2021-08-26 23:48 UTC, kalimullina commented on src/test/java/com/epam/tc/hw2/Ex1.java
> +        webDriver.manage().window().maximize();
fixed

2021-08-26 23:48 UTC, kalimullina commented on src/test/java/com/epam/tc/hw2/Ex1.java
> +    private WebElement webElement;
webElement made to local variable

2021-08-26 23:48 UTC, kalimullina commented on src/test/java/com/epam/tc/hw2/Ex1.java
> +        webElement = webDriver.findElement(By.xpath("/html/body/div/div[2]/main/div[2]/div[2]/div[1]/div/span"));
fixed

2021-08-26 23:48 UTC, kalimullina commented on src/test/java/com/epam/tc/hw2/Ex1.java
> +        webElement = webDriver.findElement(By.xpath("/html/body/div/div[2]/main/div[2]/div[2]/div[2]/div/span"));
fixed

2021-08-26 23:48 UTC, kalimullina commented on src/test/java/com/epam/tc/hw2/Ex1.java
> +        webElement = webDriver.findElement(By.xpath("/html/body/div/div[2]/main/div[2]/div[2]/div[3]/div/span"));
fixed

2021-08-26 23:48 UTC, kalimullina commented on src/test/java/com/epam/tc/hw2/Ex1.java
> +        webElement = webDriver.findElement(By.xpath("/html/body/div/div[2]/main/div[2]/div[2]/div[4]/div/span"));
fixed

2021-08-26 23:48 UTC, kalimullina commented on src/test/java/com/epam/tc/hw2/Ex2.java
> +public class Ex2 {
fixed

2021-08-26 23:48 UTC, kalimullina commented on src/test/resources/hw2/Ex1Suite.xml
> +      <class name="com.epam.tc.hw2.Ex1"/>
fixed

2021-08-27 14:27 UTC, ZeroShadows approved these changes

2021-08-27 14:29 UTC, merged